version: 2
updates:
- package-ecosystem: bundler
  directory: "/"
  schedule:
    interval: daily
    time: "10:00"
  open-pull-requests-limit: 99
  allow:
  - dependency-type: direct
  - dependency-type: indirect
  ignore:
  - dependency-name: webmock
    versions:
    - 3.11.1
    - 3.11.2
    - 3.11.3
    - 3.12.0
    - 3.12.1
  - dependency-name: faraday
    versions:
    - 1.3.0
